In [1]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import numpy as np

In [3]:
from log_conf import root_logger as logger
logger.info('Hello World')

2025-08-20 06:42:22,221 INFO     pid:85015 root:002:<module> Hello World

In [4]:
logger.debug('hello world')

In [8]:
from loguru import logger
logger.info('helo')

2025-08-17 01:09:40 | INFO     | __main__:<module>:2 - helo - {}

In [9]:
from test_logging import setup_logging
setup_logging(log_level='INFO')

2025-08-17 01:09:40 | INFO     | test_logging:setup_logging:60 - Logging configured

In [10]:
from datasets.utils2 import test_func

test_func()

2025-08-17 01:09:40 | INFO     | datasets.utils2:test_func:10 - test_info
2025-08-17 01:09:40 | ERROR    | datasets.utils2:test_func:11 - test_error
2025-08-17 01:09:40 | WARNING  | datasets.utils2:test_func:12 - test_warning
2025-08-17 01:09:40 | CRITICAL | datasets.utils2:test_func:14 - test_critical

In [12]:
from decorators import profile_function
@profile_function
def test_func2():
    for i in range(1000):
        1 == 1

test_func2()

         2 function calls in 0.000 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 /var/folders/q4/s7bw96810896_5s4r65jl0780000gn/T/ipykernel_66274/2313995711.py:2(test_func2)

In [14]:
from loguru import logger
import time

# Add context to your logs
user_id = "user_123"
logger.info(f"Processing request for user {user_id}")

# Structured logging (better for production)
logger.info("User action", user_id=user_id, action="login", timestamp=time.time())

# Exception logging with full traceback
try:
    result = 1 / 0
except Exception as e:
    logger.exception(f"Failed to process user {user_id}")  # Auto-includes traceback

2025-08-16 17:17:47.458 | INFO     | __main__:<module>:6 - Processing request for user user_123
2025-08-16 17:17:47.464 | INFO     | __main__:<module>:9 - User action
2025-08-16 17:17:47.465 | ERROR    | __main__:<module>:15 - Failed to process user user_123
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
    │   └ <bound method Application.launch_instance of <class 'ipykernel.kernelapp.IPKernelApp'>>
    └ <module 'ipykernel.kernelapp' from '/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-package...
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
    │   └ <function IPKernelApp.start at 0x1033f11c0>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x100352c30>
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
    │    │       └ <function BaseAsyncIOLoop.start at 0x1033f2160>
    │    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x1033e9a90>
    └ <ipykernel.kernelapp.IPKernelApp object at 0x100352c30>
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/tornado/platform/asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
    │    │            └ <function BaseEventLoop.run_forever at 0x1013b37e0>
    │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
    └ <tornado.platform.asyncio.AsyncIOMainLoop object at 0x1033e9a90>

  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x1013b5620>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>

  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1986, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x100f34b80>
    └ <Handle Task.task_wakeup(<Future finis...7B)>, ...],))>)>

  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finis...7B)>, ...],))>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finis...7B)>, ...],))>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finis...7B)>, ...],))>)>

  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
          │    └ <function Kernel.process_one at 0x103394680>
          └ <ipykernel.ipkernel.IPythonKernel object at 0x1033e9400>
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
          │         └ ([<zmq.Frame(b'c85832cc-a0a'...36B)>, <zmq.Frame(b'<IDS|MSG>')>, <zmq.Frame(b'c3021bc4633a'...64B)>, <zmq.Frame(b'{"date":"20...
          └ <bound method Kernel.dispatch_shell of <ipykernel.ipkernel.IPythonKernel object at 0x1033e9400>>
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
          └ <coroutine object IPythonKernel.execute_request at 0x1665a0f40>
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
                                  │       │      └ {'header': {'date': datetime.datetime(2025, 8, 16, 9, 17, 47, 271000, tzinfo=tzutc()), 'msg_id': 'edebb366-71d4-44ee-b8b9-29a...
                                  │       └ [b'c85832cc-a0a6-476f-8b57-f4c8dae327c9']
                                  └ <zmq.eventloop.zmqstream.ZMQStream object at 0x1033e9e80>
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
                          └ <coroutine object IPythonKernel.do_execute at 0x166312740>
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
          │     └ <function ZMQInteractiveShell.run_cell at 0x1033d4b80>
          └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x103973aa0>
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
                             │       └ {'store_history': True, 'silent': False, 'cell_id': 'vscode-notebook-cell:/Users/kianyewngieng/github_projects/practice_seque...
                             └ ('from loguru import logger\nimport time\n\n# Add context to your logs\nuser_id = "user_123"\nlogger.info(f"Processing reques...
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
             │    └ <function InteractiveShell._run_cell at 0x1021d5da0>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x103973aa0>
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
             │      └ <coroutine object InteractiveShell.run_cell_async at 0x16c3fba10>
             └ <function _pseudo_sync_runner at 0x1021c8f40>
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/IPython/core/async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
    │    └ <method 'send' of 'coroutine' objects>
    └ <coroutine object InteractiveShell.run_cell_async at 0x16c3fba10>
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
                       │    │             │        │     └ '/var/folders/q4/s7bw96810896_5s4r65jl0780000gn/T/ipykernel_63047/2221471999.py'
                       │    │             │        └ [<ast.ImportFrom object at 0x16c5ba490>, <ast.Import object at 0x16c5ba090>, <ast.Assign object at 0x16c5bba10>, <ast.Expr ob...
                       │    │             └ <ast.Module object at 0x16c5b9e90>
                       │    └ <function InteractiveShell.run_ast_nodes at 0x1021d60c0>
                       └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x103973aa0>
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
             │    │        │     │              └ False
             │    │        │     └ <ExecutionResult object at 16bad1130, execution_count=14 error_before_exec=None error_in_exec=None info=<ExecutionInfo object...
             │    │        └ <code object <module> at 0x16c7306f0, file "/var/folders/q4/s7bw96810896_5s4r65jl0780000gn/T/ipykernel_63047/2221471999.py", ...
             │    └ <function InteractiveShell.run_code at 0x1021d6160>
             └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x103973aa0>
  File "/Users/kianyewngieng/PycharmProjects/my_learning/learning-env/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
         │         │    │               │    └ {'__name__': '__main__', '__doc__': 'Automatically created module for IPython interactive environment', '__package__': None, ...
         │         │    │               └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x103973aa0>
         │         │    └ <property object at 0x1021d0720>
         │         └ <ipykernel.zmqshell.ZMQInteractiveShell object at 0x103973aa0>
         └ <code object <module> at 0x16c7306f0, file "/var/folders/q4/s7bw96810896_5s4r65jl0780000gn/T/ipykernel_63047/2221471999.py", ...

> File "/var/folders/q4/s7bw96810896_5s4r65jl0780000gn/T/ipykernel_63047/2221471999.py", line 13, in <module>
    result = 1 / 0

ZeroDivisionError: division by zero

In [7]:
from datetime import datetime
import pytz
local = pytz.timezone('America/Los_Angeles')
naive = datetime.now()
# naive = datetime.strptime('2001-02-03 00:00:00', '%Y-%m-%d %H:%M:%S')
print(naive)
local_dt = local.localize(naive, is_dst=None)
# --> This does not actually convert the timezone.
# ---> Need to do `astimezone(pytz.utc)` to officially cast it to the timezone
utc_dt = local_dt.astimezone(pytz.utc)
print(utc_dt)

2025-08-03 15:04:41.540974
2025-08-03 22:04:41.540974+00:00

In [4]:
utc_dt

datetime.datetime(2001, 2, 3, 8, 0, tzinfo=<UTC>)

In [6]:
n_users = 10
n_items = 5
n_rows = 100
data = pd.DataFrame(
    {
        'user_id': np.random.randint(0, n_users, n_rows),
        'item_id': np.random.randint(0, n_items, n_rows),
        'gender': np.random.randint(0, 2, n_rows),
        'age': np.random.randint(0, 100, n_rows),
        'genre': np.random.randint(0, 10, n_rows),
        'timestamp': np.random.randn(n_rows),
    }
)

In [7]:
data = data.sort_values(by=['user_id', 'timestamp'])
data.groupby(['user_id'])['item_id'].apply(list)

user_id
0    [4, 0, 4, 2, 1, 3, 2, 3, 0, 4, 0, 2, 4, 3]
1          [0, 0, 2, 3, 4, 0, 3, 0, 2, 3, 1, 1]
2       [1, 1, 3, 1, 0, 3, 3, 1, 3, 4, 4, 4, 1]
3                         [3, 0, 0, 4, 3, 4, 1]
4                   [3, 0, 2, 1, 1, 4, 1, 2, 1]
5             [0, 2, 2, 0, 1, 0, 2, 3, 3, 4, 1]
6                   [0, 4, 3, 4, 3, 4, 0, 2, 2]
7             [2, 2, 1, 3, 3, 4, 0, 2, 4, 1, 2]
8                            [3, 4, 4, 4, 0, 3]
9                      [0, 3, 0, 4, 3, 0, 4, 3]
Name: item_id, dtype: object

In [50]:
data[data['user_id'] == 0]

    user_id  item_id  gender  age  genre  timestamp
66        0        2       1   40      7  -1.555592
53        0        2       0   34      8  -1.146337
3         0        4       0   10      0  -0.605533
21        0        1       1   28      2  -0.295956
13        0        0       1   35      9   0.044033
29        0        1       0   85      3   0.121943
68        0        2       1   37      6   0.355696
72        0        1       0   89      5   0.496539
76        0        1       1   30      2   1.079398
25        0        3       0    7      1   1.280049
6         0        0       0   90      1   1.593398

In [8]:
sequences = []
for user, group in data.groupby('user_id'):
    # user_pos = row['user_pos']
    # # negative sample
    # user_neg = negative_sample(user_pos)
    # sequences.append((user_pos, user_neg))
    # user_history = row['user_history']
    break
# sequences = np.array(sequences)

In [4]:
def get_sequence(group, seq_len):
    group = group.sort_values(by='timestamp')
    seq_len = 5
    user_data = [] # (N, T, D)
    features = group.columns.tolist()
    for idx in range(len(group)):
        history = group.iloc[max(0, idx-seq_len):idx]
        row = group.iloc[idx]
        current_user = row['user_id']
        current_item = row['item_id']
        
        if len(history) < seq_len:
            remainder = seq_len - len(history)
            missing_history = np.zeros((remainder, len(history.columns)))
            user_history_len = len(history)
            history = pd.concat([pd.DataFrame(missing_history, columns=history.columns), history], ignore_index=True)
            history_mask = np.where(history == 0, 0, 1)
            user_data.append({ 'user': current_user, 
                            'gender': row['gender'],
                            'age': row['age'],
                            'timestamp': row['timestamp'],
                            'seq_len': user_history_len,
                            'sequence_info': history[['genre', 'item_id','timestamp']].to_dict(orient='list'),
                            'current_item':current_item })
    return user_data

In [ ]:
# for i in range(10):
#     print(i)

In [10]:
group = group.sort_values(by='timestamp')
seq_len = 5
user_data = [] # (N, T, D)
features = group.columns.tolist()
for idx in range(len(group)):
    history = group.iloc[max(0, idx-seq_len):idx]
    row = group.iloc[idx]
    current_user = row['user_id']
    current_item = row['item_id']
    
    if len(history) < seq_len:
        remainder = seq_len - len(history)
        missing_history = np.zeros((remainder, len(history.columns)))
        user_history_len = len(history)
        history = pd.concat([pd.DataFrame(missing_history, columns=history.columns), history], ignore_index=True)
        history_mask = np.where(history == 0, 0, 1)
        user_data.append({ 'user': current_user, 
                          'gender': row['gender'],
                          'age': row['age'],
                          'timestamp': row['timestamp'],
                          'seq_len': user_history_len,
                          'sequence_info': history[['genre', 'item_id','timestamp']].to_dict(orient='list'),
                          'current_item':current_item })

    else:
        user_data.append({ 'user': current_user, 
                    'gender': row['gender'],
                    'age': row['age'],
                    'timestamp': row['timestamp'],
                    'seq_len': user_history_len,
                    'sequence_info': history[['genre', 'item_id','timestamp']].to_dict(orient='list'),
                    'current_item':current_item }) 
    # if idx == 6:
    #     break

In [81]:
len(group)

11

In [8]:
df = pd.DataFrame(user_data)

In [9]:
df

,user,gender,age,timestamp,seq_len,sequence_info,current_item
0,0.0,1.0,6.0,-1.568714,0,"{'genre': [0.0, 0.0, 0.0, 0.0, 0.0], 'item_id'...",2.0
1,0.0,0.0,67.0,-0.779642,1,"{'genre': [0.0, 0.0, 0.0, 0.0, 8.0], 'item_id'...",3.0
2,0.0,1.0,68.0,-0.719245,2,"{'genre': [0.0, 0.0, 0.0, 8.0, 2.0], 'item_id'...",1.0
3,0.0,1.0,81.0,-0.297680,3,"{'genre': [0.0, 0.0, 8.0, 2.0, 9.0], 'item_id'...",4.0
4,0.0,1.0,88.0,-0.056068,4,"{'genre': [0.0, 8.0, 2.0, 9.0, 5.0], 'item_id'...",2.0
5,0.0,0.0,56.0,0.230330,4,"{'genre': [8, 2, 9, 5, 6], 'item_id': [2, 3, 1...",1.0
6,0.0,0.0,51.0,0.310838,4,"{'genre': [2, 9, 5, 6, 9], 'item_id': [3, 1, 4...",0.0
7,0.0,0.0,87.0,0.497950,4,"{'genre': [9, 5, 6, 9, 7], 'item_id': [1, 4, 2...",1.0
8,0.0,1.0,2.0,0.968389,4,"{'genre': [5, 6, 9, 7, 7], 'item_id': [4, 2, 1...",0.0

In [ ]:
# categorical_features

In [11]:
import torch
import torch.nn as nn

class DataSet(torch.utils.data.Dataset):
    def __init__(self, df):
        super().__init__()
        self.df = df
        
    def __getitem__(self, idx):
        row = self.df[idx]
        return row # dict
    
    def __len__(self):
        return len(self.df)

dataset = DataSet(user_data)
dataset[0]

{'user': 0.0,
 'gender': 0.0,
 'age': 10.0,
 'timestamp': -1.7427612154087795,
 'seq_len': 0,
 'sequence_info': {'genre': [0.0, 0.0, 0.0, 0.0, 0.0],
  'item_id': [0.0, 0.0, 0.0, 0.0, 0.0],
  'timestamp': [0.0, 0.0, 0.0, 0.0, 0.0]},
 'current_item': 4.0}

In [139]:
def collate_fn(batch):
    return batch

In [ ]:
def melt(self, df, id_vars, value_vars, var_name='variable', value_name='value'):
    """Function to melt spark dataframe from wide to long
    
    Args:
        df (DataFrame)
        id_vars (List[str]) columns to keep
        value_vars (List[str]) columns to unpivot on
        var_name (str): Name to use for 'variable' columns
        value_name (str): Name to use for 'value' columns
        
    Returns:
        (DataFrame)
    """
    # Create array<struct<variable: str, vale:...>>
    _vars_and_vals = F.array(*(
        F.struct(F.lit(c).alias(var_name), F.col(c).alias(value_name)) for c in value_vars
    ))
    
    # Add to dataframe and explode
    _tmp = df.withColumn("_vars_and_vals", F.explode(_vars_and_vals))
    cols = id_vars + [
        F.col('_vars_and_vals')[x].alias(x) for x in [var_name, value_name]
    ]
    return _tmp.select(*cols)
    
[{'key': col1, 'value': col1value, 'key': }]

In [ ]:
import joblib
    
class DataProcessor:
    def __init__(self, config: Dict, **kwargs):
        self.config = config
        self.numerical_encoder = self.kwargs.get('numerical_encoder', self.load_numerical_encoder(self.config['numerical_encoder']))
        self.categorical_encoder = self.kwargs.get('categorical_encoder', self.load_categorical_encoder(self.config['categorical_encoder']))

    def load_numerical_encoder(self, path):
        numerical_encoder = NumericalEncoder(self.config['numerical_features'])
        return numerical_encoder

    def load_categorical_encoder(self, path):
        categorical_encoder = CategoricalEncoder(self.config['categorical_features'])
        return categorical_encoder

    def fit_numerical_encoder(self, df):
        self.numerical_encoder.fit(df[self.config['numerical_features']])
        df[self.config['numerical_features']] = self.numerical_encoder.transform(df[self.config['numerical_features']])
        return df

    def fit_categorical_encoder(self, df):
        self.categorical_encoder.fit(df[self.config['categorical_features']])
        df[self.config['categorical_features']] = self.categorical_encoder.transform(df[self.config['categorical_features']])
        return df
     
    def fit(self, train_df):
        self.fit_numerical_encoder(train_df)
        self.fit_categorical_encoder(train_df)
        return 
    
    def process(self, df):
        df = self.numerical_encoder.transform(df)
        df = self.categorical_encoder.transform(df)
        return df

    def transform(self, df):
        df = self.numerical_encoder.transform(df)
        df = self.categorical_encoder.transform(df)
        return df 
    
    def save(self, path: str) -> None:
        """Save entire processor state in one file"""
        state = {
            'config': self.config,
            'is_initialized': self.is_initialized,
            'numerical_encoder': self.numerical_encoder,
            'categorical_encoder': self.categorical_encoder,
            'version': '1.0',
            'timestamp': datetime.now().isoformat()
        }
        
        joblib.dump(state, path)
        logger.info(f"Saved complete processor state to: {path}")
    
    def load(self, path: str) -> 'DataProcessor':
        """Load complete processor state from one file"""
        if not Path(path).exists():
            raise FileNotFoundError(f"Processor file not found: {path}")
        
        try:
            state = joblib.load(path)
            
            # Restore state
            self.config = state['config']
            self.is_initialized = state['is_initialized']
            self.numerical_encoder = state['numerical_encoder']
            self.categorical_encoder = state['categorical_encoder']
            
            logger.info(f"Loaded complete processor state from: {path}")
            return self
            
        except Exception as e:
            raise ValueError(f"Failed to load processor from {path}: {e}")
    
    @classmethod
    def from_file(cls, path: str) -> 'DataProcessor':
        """Create processor instance from saved file"""
        if not Path(path).exists():
            raise FileNotFoundError(f"Processor file not found: {path}")
        
        try:
            state = joblib.load(path)
            processor = cls(state['config'])
            
            # Restore state
            processor.is_initialized = state['is_initialized']
            processor.numerical_encoder = state['numerical_encoder']
            processor.categorical_encoder = state['categorical_encoder']
            
            return processor
            
        except Exception as e:
            raise ValueError(f"Failed to create processor from {path}: {e}")

dp = DataProcessor(config, numerical_encoder=NumericalEncoder), categorical_encoder=CategoricalEncoder))
dp.fit(train)
dp.save('data_processor.pkl')
dp.load('data_processor.pkl')
train = dp.transform(train)
valid = dp.transform(valid)
test = dp.transform(test)

In [13]:
dataloader = torch.utils.data.DataLoader(dataset, batch_size=7, shuffle=True)
batch = next(iter(dataloader))

In [178]:
batch['sequence_info'].keys()

dict_keys(['genre', 'item_id', 'timestamp'])

In [21]:
import torch
import torch.nn as nn

class DataSet(torch.utils.data.Dataset):
    def __init__(self, df):
        super().__init__()
        self.df = df
        
    def __getitem__(self, idx):
        row = self.df[idx]
        return row # dict
    
    def __len__(self):
        return len(self.df)

dataset = DataSet(user_data)
dataset[0]

{'user': 0.0,
 'gender': 0.0,
 'age': 10.0,
 'timestamp': -1.7427612154087795,
 'seq_len': 0,
 'sequence_info': {'genre': [0.0, 0.0, 0.0, 0.0, 0.0],
  'item_id': [0.0, 0.0, 0.0, 0.0, 0.0],
  'timestamp': [0.0, 0.0, 0.0, 0.0, 0.0]},
 'current_item': 4.0}

In [16]:
categorical_features = ['gender', 'genre']

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.genre_hist_emb  = nn.Embedding(10, 10)
        self.current_item_emb = nn.Embedding(10, 10)
        self.item_hist_emb = nn.Embedding(10, 10)
        
    def forward(self, x):
        current_item_emb = self.current_item_emb(x['current_item'].type(torch.long))
        history_emb = self.genre_hist_emb(torch.stack(x['sequence_info']['genre']).T.type(torch.long))
        return current_item_emb, history_emb
    
    @classmethod
    def get_pretrained_model(cls, model_path, map_location=None):
        model_data = torch.load(model_path, map_location=map_location)
        model.load_state_dict(model_data)
        model.eval()
        for p in model.parameters():
            p.requires_grad_(False)
        return model

    def save_model(self, model_path):
        torch.save(self.state_dict(), model_path)
        logger.info(f'Model {self.__class__.__name__} saved to {model_path}')
        return

model = Model()
model(batch)[0].shape # B, T, D

torch.Size([7, 10])

In [15]:
model.save_model('model.pth')

2025-08-16 17:41:32 | INFO     | __main__ - Model Model saved to model.pth

In [ ]:
loaded_model = model.get_pretrained_model('model.pth')
# loaded_model.genre_hist_emb.weight.requires_grad

/var/folders/q4/s7bw96810896_5s4r65jl0780000gn/T/ipykernel_63952/4187463490.py:17: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model_data = torch.load(model_path, map_location=map_location)

False

In [ ]:
model.load

In [ ]:
current_emb = model(batch)[0] # (B, D)
history_emb = model(batch)[1] # (B, T, D)
query = current_emb
history_emb = history_emb
q,k,v = nn.Linear(10, 10), nn.Linear(10, 10), nn.Linear(10, 10)
# (B, 1, T) -> attention of current item to previous items

In [ ]:
max_seq_len = len(batch['sequence_info']['genre'])
lengths = torch.arange(max_seq_len) # (T)
mask = lengths.reshape(1,-1) < batch['seq_len'].reshape(-1,1) # (T,), (B,) -> (B, T)
mask # (B, T)

In [174]:
def collate_fn(batch):
    print(type(batch), len(batch))
    # batch: list of data from Dataset 
    keys = batch[0].keys()
    new_dict = {}
    for key in keys:
        if key != 'sequence_info':
            new_dict[key] = torch.tensor([item[key] for item in batch])
        else:
            new_dict['sequence_info'] = {}
            for sub_key in batch[0]['sequence_info'].keys():
                new_dict['sequence_info'][sub_key] = torch.tensor([item['sequence_info'][sub_key] for item in batch])
    return new_dict

dataloader2 = torch.utils.data.DataLoader(dataset, batch_size=7, shuffle=True, collate_fn=collate_fn)
batch2 = next(iter(dataloader2))
batch2

<class 'list'> 7

{'user': tensor([0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64),
 'gender': tensor([0., 1., 1., 0., 1., 0., 1.], dtype=torch.float64),
 'age': tensor([89., 28., 30., 90., 37., 85., 40.], dtype=torch.float64),
 'timestamp': tensor([ 0.4965, -0.2960,  1.0794,  1.5934,  0.3557,  0.1219, -1.5556],
        dtype=torch.float64),
 'seq_len': tensor([4, 3, 4, 4, 4, 4, 0]),
 'sequence_info': {'genre': tensor([[0., 2., 9., 3., 6.],
          [0., 0., 7., 8., 0.],
          [2., 9., 3., 6., 5.],
          [3., 6., 5., 2., 1.],
          [8., 0., 2., 9., 3.],
          [7., 8., 0., 2., 9.],
          [0., 0., 0., 0., 0.]]),
  'item_id': tensor([[4., 1., 0., 1., 2.],
          [0., 0., 2., 2., 4.],
          [1., 0., 1., 2., 1.],
          [1., 2., 1., 1., 3.],
          [2., 4., 1., 0., 1.],
          [2., 2., 4., 1., 0.],
          [0., 0., 0., 0., 0.]]),
  'timestamp': tensor([[-0.6055, -0.2960,  0.0440,  0.1219,  0.3557],
          [ 0.0000,  0.0000, -1.5556, -1.1463, -0.6055],
          [-0.2960,  0.0440,  0.1219,  0.3557,  0.4965],
          [ 0.1219,  0.3557,  0.4965,  1.0794,  1.2800],
          [-1.1463, -0.6055, -0.2960,  0.0440,  0.1219],
          [-1.5556, -1.1463, -0.6055, -0.2960,  0.0440],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])},
 'current_item': tensor([1., 1., 1., 0., 2., 1., 2.], dtype=torch.float64)}

In [147]:
emb = nn.Embedding(10, 10)
cat = torch.stack(batch['sequence_info']['genre']).T.type(torch.long) # (B, T)

emb(cat).shape # (B, T, 1)

torch.Size([7, 5, 10])

In [153]:
batch['seq_len']

tensor([3, 0, 4, 4, 2, 4, 4])

tensor([[ True,  True,  True, False, False],
        [False, False, False, False, False],
        [ True,  True,  True,  True, False],
        [ True,  True,  True,  True, False],
        [ True,  True, False, False, False],
        [ True,  True,  True,  True, False],
        [ True,  True,  True,  True, False]])

In [164]:
batch

{'user': tensor([0., 0., 0., 0., 0., 0., 0.], dtype=torch.float64),
 'gender': tensor([1., 1., 0., 0., 0., 1., 0.], dtype=torch.float64),
 'age': tensor([28., 40.,  7., 90., 10., 35., 85.], dtype=torch.float64),
 'timestamp': tensor([-0.2960, -1.5556,  1.2800,  1.5934, -0.6055,  0.0440,  0.1219],
        dtype=torch.float64),
 'seq_len': tensor([3, 0, 4, 4, 2, 4, 4]),
 'sequence_info': {'genre': [tensor([0., 0., 9., 3., 0., 0., 7.], dtype=torch.float64),
   tensor([0., 0., 3., 6., 0., 7., 8.], dtype=torch.float64),
   tensor([7., 0., 6., 5., 0., 8., 0.], dtype=torch.float64),
   tensor([8., 0., 5., 2., 7., 0., 2.], dtype=torch.float64),
   tensor([0., 0., 2., 1., 8., 2., 9.], dtype=torch.float64)],
  'item_id': [tensor([0., 0., 0., 1., 0., 0., 2.], dtype=torch.float64),
   tensor([0., 0., 1., 2., 0., 2., 2.], dtype=torch.float64),
   tensor([2., 0., 2., 1., 0., 2., 4.], dtype=torch.float64),
   tensor([2., 0., 1., 1., 2., 4., 1.], dtype=torch.float64),
   tensor([4., 0., 1., 3., 2., 1., 0.], dtype=torch.float64)],
  'timestamp': [tensor([ 0.0000,  0.0000,  0.0440,  0.1219,  0.0000,  0.0000, -1.5556],
          dtype=torch.float64),
   tensor([ 0.0000,  0.0000,  0.1219,  0.3557,  0.0000, -1.5556, -1.1463],
          dtype=torch.float64),
   tensor([-1.5556,  0.0000,  0.3557,  0.4965,  0.0000, -1.1463, -0.6055],
          dtype=torch.float64),
   tensor([-1.1463,  0.0000,  0.4965,  1.0794, -1.5556, -0.6055, -0.2960],
          dtype=torch.float64),
   tensor([-0.6055,  0.0000,  1.0794,  1.2800, -1.1463, -0.2960,  0.0440],
          dtype=torch.float64)]},
 'current_item': tensor([1., 2., 3., 0., 4., 0., 1.], dtype=torch.float64)}

In [161]:
lengths

tensor([0, 1, 2, 3, 4])

In [163]:
batch['seq_len']

tensor([3, 0, 4, 4, 2, 4, 4])

In [95]:
pd.DataFrame(user_data).to_parquet('test.parquet')

In [93]:
df = pd.DataFrame(user_data)
df['kv_pairs'] = df['sequence_info'].apply(lambda x: list(x.items()))
df['kv_pairs']
df_exploded = df.explode('kv_pairs')
df_exploded

,user,gender,age,timestamp,seq_len,sequence_info,current_item,kv_pairs
0,0.0,1.0,40.0,-1.555592,0,"{'genre': [0.0, 0.0, 0.0, 0.0, 0.0], 'item_id'...",2.0,"(genre, [0.0, 0.0, 0.0, 0.0, 0.0])"
0,0.0,1.0,40.0,-1.555592,0,"{'genre': [0.0, 0.0, 0.0, 0.0, 0.0], 'item_id'...",2.0,"(item_id, [0.0, 0.0, 0.0, 0.0, 0.0])"
0,0.0,1.0,40.0,-1.555592,0,"{'genre': [0.0, 0.0, 0.0, 0.0, 0.0], 'item_id'...",2.0,"(timestamp, [0.0, 0.0, 0.0, 0.0, 0.0])"
1,0.0,0.0,34.0,-1.146337,1,"{'genre': [0.0, 0.0, 0.0, 0.0, 7.0], 'item_id'...",2.0,"(genre, [0.0, 0.0, 0.0, 0.0, 7.0])"
1,0.0,0.0,34.0,-1.146337,1,"{'genre': [0.0, 0.0, 0.0, 0.0, 7.0], 'item_id'...",2.0,"(item_id, [0.0, 0.0, 0.0, 0.0, 2.0])"
1,0.0,0.0,34.0,-1.146337,1,"{'genre': [0.0, 0.0, 0.0, 0.0, 7.0], 'item_id'...",2.0,"(timestamp, [0.0, 0.0, 0.0, 0.0, -1.5555917845..."
2,0.0,0.0,10.0,-0.605533,2,"{'genre': [0.0, 0.0, 0.0, 7.0, 8.0], 'item_id'...",4.0,"(genre, [0.0, 0.0, 0.0, 7.0, 8.0])"
2,0.0,0.0,10.0,-0.605533,2,"{'genre': [0.0, 0.0, 0.0, 7.0, 8.0], 'item_id'...",4.0,"(item_id, [0.0, 0.0, 0.0, 2.0, 2.0])"
2,0.0,0.0,10.0,-0.605533,2,"{'genre': [0.0, 0.0, 0.0, 7.0, 8.0], 'item_id'...",4.0,"(timestamp, [0.0, 0.0, 0.0, -1.555591784566406..."
3,0.0,1.0,28.0,-0.295956,3,"{'genre': [0.0, 0.0, 7.0, 8.0, 0.0], 'item_id'...",1.0,"(genre, [0.0, 0.0, 7.0, 8.0, 0.0])"
3,0.0,1.0,28.0,-0.295956,3,"{'genre': [0.0, 0.0, 7.0, 8.0, 0.0], 'item_id'...",1.0,"(item_id, [0.0, 0.0, 2.0, 2.0, 4.0])"
3,0.0,1.0,28.0,-0.295956,3,"{'genre': [0.0, 0.0, 7.0, 8.0, 0.0], 'item_id'...",1.0,"(timestamp, [0.0, 0.0, -1.5555917845664062, -1..."
4,0.0,1.0,35.0,0.044033,4,"{'genre': [0.0, 7.0, 8.0, 0.0, 2.0], 'item_id'...",0.0,"(genre, [0.0, 7.0, 8.0, 0.0, 2.0])"
4,0.0,1.0,35.0,0.044033,4,"{'genre': [0.0, 7.0, 8.0, 0.0, 2.0], 'item_id'...",0.0,"(item_id, [0.0, 2.0, 2.0, 4.0, 1.0])"
4,0.0,1.0,35.0,0.044033,4,"{'genre': [0.0, 7.0, 8.0, 0.0, 2.0], 'item_id'...",0.0,"(timestamp, [0.0, -1.5555917845664062, -1.1463..."
5,0.0,0.0,85.0,0.121943,4,"{'genre': [7, 8, 0, 2, 9], 'item_id': [2, 2, 4...",1.0,"(genre, [7, 8, 0, 2, 9])"
5,0.0,0.0,85.0,0.121943,4,"{'genre': [7, 8, 0, 2, 9], 'item_id': [2, 2, 4...",1.0,"(item_id, [2, 2, 4, 1, 0])"
5,0.0,0.0,85.0,0.121943,4,"{'genre': [7, 8, 0, 2, 9], 'item_id': [2, 2, 4...",1.0,"(timestamp, [-1.5555917845664062, -1.146337093..."
6,0.0,1.0,37.0,0.355696,4,"{'genre': [8, 0, 2, 9, 3], 'item_id': [2, 4, 1...",2.0,"(genre, [8, 0, 2, 9, 3])"
6,0.0,1.0,37.0,0.355696,4,"{'genre': [8, 0, 2, 9, 3], 'item_id': [2, 4, 1...",2.0,"(item_id, [2, 4, 1, 0, 1])"
6,0.0,1.0,37.0,0.355696,4,"{'genre': [8, 0, 2, 9, 3], 'item_id': [2, 4, 1...",2.0,"(timestamp, [-1.1463370939048667, -0.605533224..."
7,0.0,0.0,89.0,0.496539,4,"{'genre': [0, 2, 9, 3, 6], 'item_id': [4, 1, 0...",1.0,"(genre, [0, 2, 9, 3, 6])"
7,0.0,0.0,89.0,0.496539,4,"{'genre': [0, 2, 9, 3, 6], 'item_id': [4, 1, 0...",1.0,"(item_id, [4, 1, 0, 1, 2])"
7,0.0,0.0,89.0,0.496539,4,"{'genre': [0, 2, 9, 3, 6], 'item_id': [4, 1, 0...",1.0,"(timestamp, [-0.6055332245598174, -0.295955745..."
8,0.0,1.0,30.0,1.079398,4,"{'genre': [2, 9, 3, 6, 5], 'item_id': [1, 0, 1...",1.0,"(genre, [2, 9, 3, 6, 5])"
8,0.0,1.0,30.0,1.079398,4,"{'genre': [2, 9, 3, 6, 5], 'item_id': [1, 0, 1...",1.0,"(item_id, [1, 0, 1, 2, 1])"
8,0.0,1.0,30.0,1.079398,4,"{'genre': [2, 9, 3, 6, 5], 'item_id': [1, 0, 1...",1.0,"(timestamp, [-0.2959557450685174, 0.0440325042..."
9,0.0,0.0,7.0,1.280049,4,"{'genre': [9, 3, 6, 5, 2], 'item_id': [0, 1, 2...",3.0,"(genre, [9, 3, 6, 5, 2])"
9,0.0,0.0,7.0,1.280049,4,"{'genre': [9, 3, 6, 5, 2], 'item_id': [0, 1, 2...",3.0,"(item_id, [0, 1, 2, 1, 1])"
9,0.0,0.0,7.0,1.280049,4,"{'genre': [9, 3, 6, 5, 2], 'item_id': [0, 1, 2...",3.0,"(timestamp, [0.044032504240912845, 0.121942826..."
10,0.0,0.0,90.0,1.593398,4,"{'genre': [3, 6, 5, 2, 1], 'item_id': [1, 2, 1...",0.0,"(genre, [3, 6, 5, 2, 1])"
10,0.0,0.0,90.0,1.593398,4,"{'genre': [3, 6, 5, 2, 1], 'item_id': [1, 2, 1...",0.0,"(item_id, [1, 2, 1, 1, 3])"
10,0.0,0.0,90.0,1.593398,4,"{'genre': [3, 6, 5, 2, 1], 'item_id': [1, 2, 1...",0.0,"(timestamp, [0.12194282687801519, 0.3556955499..."

In [94]:
pd.DataFrame(df_exploded['kv_pairs'].tolist(), index=df_exploded.index)

            0                                                  1
0       genre                          [0.0, 0.0, 0.0, 0.0, 0.0]
0     item_id                          [0.0, 0.0, 0.0, 0.0, 0.0]
0   timestamp                          [0.0, 0.0, 0.0, 0.0, 0.0]
1       genre                          [0.0, 0.0, 0.0, 0.0, 7.0]
1     item_id                          [0.0, 0.0, 0.0, 0.0, 2.0]
1   timestamp          [0.0, 0.0, 0.0, 0.0, -1.5555917845664062]
2       genre                          [0.0, 0.0, 0.0, 7.0, 8.0]
2     item_id                          [0.0, 0.0, 0.0, 2.0, 2.0]
2   timestamp  [0.0, 0.0, 0.0, -1.5555917845664062, -1.146337...
3       genre                          [0.0, 0.0, 7.0, 8.0, 0.0]
3     item_id                          [0.0, 0.0, 2.0, 2.0, 4.0]
3   timestamp  [0.0, 0.0, -1.5555917845664062, -1.14633709390...
4       genre                          [0.0, 7.0, 8.0, 0.0, 2.0]
4     item_id                          [0.0, 2.0, 2.0, 4.0, 1.0]
4   timestamp  [0.0, -1.5555917845664062, -1.1463370939048667...
5       genre                                    [7, 8, 0, 2, 9]
5     item_id                                    [2, 2, 4, 1, 0]
5   timestamp  [-1.5555917845664062, -1.1463370939048667, -0....
6       genre                                    [8, 0, 2, 9, 3]
6     item_id                                    [2, 4, 1, 0, 1]
6   timestamp  [-1.1463370939048667, -0.6055332245598174, -0....
7       genre                                    [0, 2, 9, 3, 6]
7     item_id                                    [4, 1, 0, 1, 2]
7   timestamp  [-0.6055332245598174, -0.2959557450685174, 0.0...
8       genre                                    [2, 9, 3, 6, 5]
8     item_id                                    [1, 0, 1, 2, 1]
8   timestamp  [-0.2959557450685174, 0.044032504240912845, 0....
9       genre                                    [9, 3, 6, 5, 2]
9     item_id                                    [0, 1, 2, 1, 1]
9   timestamp  [0.044032504240912845, 0.12194282687801519, 0....
10      genre                                    [3, 6, 5, 2, 1]
10    item_id                                    [1, 2, 1, 1, 3]
10  timestamp  [0.12194282687801519, 0.3556955499372465, 0.49...

In [83]:
user_data

[{'user': 0.0,
  'gender': 1.0,
  'age': 40.0,
  'timestamp': -1.5555917845664062,
  'seq_len': 0,
  'sequence_info': {'genre': [0.0, 0.0, 0.0, 0.0, 0.0],
   'item_id': [0.0, 0.0, 0.0, 0.0, 0.0],
   'timestamp': [0.0, 0.0, 0.0, 0.0, 0.0]},
  'current_item': 2.0},
 {'user': 0.0,
  'gender': 0.0,
  'age': 34.0,
  'timestamp': -1.1463370939048667,
  'seq_len': 1,
  'sequence_info': {'genre': [0.0, 0.0, 0.0, 0.0, 7.0],
   'item_id': [0.0, 0.0, 0.0, 0.0, 2.0],
   'timestamp': [0.0, 0.0, 0.0, 0.0, -1.5555917845664062]},
  'current_item': 2.0},
 {'user': 0.0,
  'gender': 0.0,
  'age': 10.0,
  'timestamp': -0.6055332245598174,
  'seq_len': 2,
  'sequence_info': {'genre': [0.0, 0.0, 0.0, 7.0, 8.0],
   'item_id': [0.0, 0.0, 0.0, 2.0, 2.0],
   'timestamp': [0.0, 0.0, 0.0, -1.5555917845664062, -1.1463370939048667]},
  'current_item': 4.0},
 {'user': 0.0,
  'gender': 1.0,
  'age': 28.0,
  'timestamp': -0.2959557450685174,
  'seq_len': 3,
  'sequence_info': {'genre': [0.0, 0.0, 7.0, 8.0, 0.0],
   'item_id': [0.0, 0.0, 2.0, 2.0, 4.0],
   'timestamp': [0.0,
    0.0,
    -1.5555917845664062,
    -1.1463370939048667,
    -0.6055332245598174]},
  'current_item': 1.0},
 {'user': 0.0,
  'gender': 1.0,
  'age': 35.0,
  'timestamp': 0.044032504240912845,
  'seq_len': 4,
  'sequence_info': {'genre': [0.0, 7.0, 8.0, 0.0, 2.0],
   'item_id': [0.0, 2.0, 2.0, 4.0, 1.0],
   'timestamp': [0.0,
    -1.5555917845664062,
    -1.1463370939048667,
    -0.6055332245598174,
    -0.2959557450685174]},
  'current_item': 0.0},
 {'user': 0.0,
  'gender': 0.0,
  'age': 85.0,
  'timestamp': 0.12194282687801519,
  'seq_len': 4,
  'sequence_info': {'genre': [7, 8, 0, 2, 9],
   'item_id': [2, 2, 4, 1, 0],
   'timestamp': [-1.5555917845664062,
    -1.1463370939048667,
    -0.6055332245598174,
    -0.2959557450685174,
    0.044032504240912845]},
  'current_item': 1.0},
 {'user': 0.0,
  'gender': 1.0,
  'age': 37.0,
  'timestamp': 0.3556955499372465,
  'seq_len': 4,
  'sequence_info': {'genre': [8, 0, 2, 9, 3],
   'item_id': [2, 4, 1, 0, 1],
   'timestamp': [-1.1463370939048667,
    -0.6055332245598174,
    -0.2959557450685174,
    0.044032504240912845,
    0.12194282687801519]},
  'current_item': 2.0},
 {'user': 0.0,
  'gender': 0.0,
  'age': 89.0,
  'timestamp': 0.4965389100644229,
  'seq_len': 4,
  'sequence_info': {'genre': [0, 2, 9, 3, 6],
   'item_id': [4, 1, 0, 1, 2],
   'timestamp': [-0.6055332245598174,
    -0.2959557450685174,
    0.044032504240912845,
    0.12194282687801519,
    0.3556955499372465]},
  'current_item': 1.0},
 {'user': 0.0,
  'gender': 1.0,
  'age': 30.0,
  'timestamp': 1.07939836228451,
  'seq_len': 4,
  'sequence_info': {'genre': [2, 9, 3, 6, 5],
   'item_id': [1, 0, 1, 2, 1],
   'timestamp': [-0.2959557450685174,
    0.044032504240912845,
    0.12194282687801519,
    0.3556955499372465,
    0.4965389100644229]},
  'current_item': 1.0},
 {'user': 0.0,
  'gender': 0.0,
  'age': 7.0,
  'timestamp': 1.2800490405727953,
  'seq_len': 4,
  'sequence_info': {'genre': [9, 3, 6, 5, 2],
   'item_id': [0, 1, 2, 1, 1],
   'timestamp': [0.044032504240912845,
    0.12194282687801519,
    0.3556955499372465,
    0.4965389100644229,
    1.07939836228451]},
  'current_item': 3.0},
 {'user': 0.0,
  'gender': 0.0,
  'age': 90.0,
  'timestamp': 1.59339831915241,
  'seq_len': 4,
  'sequence_info': {'genre': [3, 6, 5, 2, 1],
   'item_id': [1, 2, 1, 1, 3],
   'timestamp': [0.12194282687801519,
    0.3556955499372465,
    0.4965389100644229,
    1.07939836228451,
    1.2800490405727953]},
  'current_item': 0.0}]

In [77]:
user_data[-1]

{'user': 0.0,
 'gender': 1.0,
 'age': 35.0,
 'timestamp': 0.044032504240912845,
 'seq_len': 4,
 'sequence_info': {'genre': [0.0, 7.0, 8.0, 0.0, 2.0],
  'item_id': [0.0, 2.0, 2.0, 4.0, 1.0],
  'timestamp': [0.0,
   -1.5555917845664062,
   -1.1463370939048667,
   -0.6055332245598174,
   -0.2959557450685174]},
 'current_item': 0.0}

In [75]:
user_data[0]['features']

{'user_id': [0.0, 0.0, 0.0, 0.0, 0.0],
 'item_id': [0.0, 0.0, 0.0, 0.0, 0.0],
 'gender': [0.0, 0.0, 0.0, 0.0, 0.0],
 'age': [0.0, 0.0, 0.0, 0.0, 0.0],
 'genre': [0.0, 0.0, 0.0, 0.0, 0.0],
 'timestamp': [0.0, 0.0, 0.0, 0.0, 0.0]}

In [80]:
import torch
import torch.nn as nn

torch.tensor(list(user_data[0]['features'].values()))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
user2id = {}
item2id = {}

In [ ]:
session_id # ids will always be new

In [55]:
history_mask

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [42]:
remainder

1

In [ ]:
history.shape

(5, 6)

In [37]:
data.iloc[:0]

Empty DataFrame
Columns: [user_id, item_id, gender, age, genre, timestamp]
Index: []

In [50]:
user_data[]

IndexError: list index out of range

In [30]:
history

   user_id  item_id  gender  age  genre  timestamp
0      0.0      0.0     0.0  0.0    0.0        0.0
1      0.0      0.0     0.0  0.0    0.0        0.0
2      0.0      0.0     0.0  0.0    0.0        0.0
3      0.0      0.0     0.0  0.0    0.0        0.0
4      0.0      0.0     0.0  0.0    0.0        0.0

In [15]:
history.shape

(0, 6)

In [25]:
remainder = seq_len - len(history)
history2 = np.concatenate([np.zeros((remainder, len(history.columns))), history])
history = pd.concat([pd.DataFrame(history2, columns=history.columns), history], ignore_index=True)

   user_id  item_id  gender  age  genre  timestamp
0      0.0      0.0     0.0  0.0    0.0        0.0
1      0.0      0.0     0.0  0.0    0.0        0.0
2      0.0      0.0     0.0  0.0    0.0        0.0
3      0.0      0.0     0.0  0.0    0.0        0.0
4      0.0      0.0     0.0  0.0    0.0        0.0